### ISSUE TITLE
有没有详细一点的文档说明呢？

### ISSUE THREAD

**Issue by OranTing** [guojiangclub/laravel-sms#3]

**Comment by OranTing** [comment]
研究了一遍，阿里云的短信接口跑通了。
需要把sms 的 config里的 data里的 product 指定值。但是容联云通讯的还是无法使用。有没有说明呢？
谢谢。
```
 'data' => [
        'product' => '',
    ]
```

**Comment by chenbidepro** [comment]
请升级1.4.0，并且查看  https://github.com/ibrandcc/laravel-sms#%E5%AE%9A%E4%B9%89%E7%9F%AD%E4%BF%A1
